version: "3.9"

services:
  redis:
    image: redis/redis-stack:7.2.0
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  app:
    build: .
    container_name: grievance_app
    ports:
      - "8501:8501"
    depends_on:
      - redis
    volumes:
      - ./data/files:/data/files